### PR TITLE
ghcr repo and ghcr repo owner to lowercase

### PR DESCRIPTION
**Pull request by darodi**
to prevent error:
   Error: buildx failed with: error: invalid tag "ghcr.io/User/project:2022.04.09_linux_amd64_nohealthcheck": repository name must be lowercase

### CODE REVIEW

**Comment by mikenye** [comment]
Thanks for this! Out of curiosity, what are you using these workflows for?

**Comment by darodi** [comment]
I'm using it to build a multi arch docker image for 
https://github.com/darodi/docker-py3.8-slim-buster-pikepdf

and then that base image is used in this project
https://github.com/Xonshiz/comic-dl

**Comment by mikenye** [comment]
Sorry, please bear with me while I try and fix the test workflow...

**Comment by darodi** [comment]
Thanks a lot.

**Comment by mikenye** [comment]
You’re welcome! Thanks for the contribution.

**Pull request merged**
